#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tursibNow.AndroidUI.Resource", IsApplication=true)]

namespace tursibNow.AndroidUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::tursibNow.Core.Resource.String.ApplicationName = global::tursibNow.AndroidUI.Resource.String.ApplicationName;
			global::tursibNow.Core.Resource.String.Hello = global::tursibNow.AndroidUI.Resource.String.Hello;
			global::tursibNow.Model.Resource.String.ApplicationName = global::tursibNow.AndroidUI.Resource.String.ApplicationName;
			global::tursibNow.Model.Resource.String.Hello = global::tursibNow.AndroidUI.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_favorite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int BusNameTextView = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int BusNoTextView = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int BusOverviewLinearLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int BusOverviewListView = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int BusSearchArrival = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int BusSearchAutoCompleteArrival = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int BusSearchAutoCompleteDeparture = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int BusSearchButton = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int BusSearchDeparture = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int BusSearchResultsItemBusName = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int BusSearchResultsItemDepartureStationName = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int BusSearchResultsItemDepartureTimes = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int BusSearchResultsListView = 2131099659;
			
			// aapt resource value: 0x7f060018
			public const int BusTimetableSaturday = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int BusTimetableSunday = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int BusTimetableWeekdays = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int StationNameTextView = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int StationsSaturdayTextView = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int StationsSundayTextView = 2131099677;
			
			// aapt resource value: 0x7f060015
			public const int StationsWeekdaysTextView = 2131099669;
			
			// aapt resource value: 0x7f060020
			public const int addFavoriteStation = 2131099680;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout3 = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout4 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int list_header_title = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int list_item_title = 2131099679;
			
			// aapt resource value: 0x7f060009
			public const int relativeLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int scrollView1 = 2131099665;
			
			// aapt resource value: 0x7f060021
			public const int searchBuses = 2131099681;
			
			// aapt resource value: 0x7f060012
			public const int tableLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int tableRow1 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int tableRow2 = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int tableRow3 = 2131099674;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BusOverview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BusOverviewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BusSearch = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BusSearchResults = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BusSearchResultsItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BusStationsItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BusTimetable = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListHeader = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int AddFavoriteStation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SearchBuses = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int Arrival = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int ArrivalMessage = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int BusSearch = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int Departure = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int DepartureMessage = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int DirectRoutes = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int InvalidStationMessage = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int InvalidStationTitle = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int ReverseRoutes = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int Saturday = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int Search = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int Sunday = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int Weekdays = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
